// src_cef/src/views/donate/main/popup/popupchange.svelte
<script>
    import { executeClient } from 'api/rage'
    import { accountRedbucks } from 'store/account'
    import { serverDonateDoubleConvert } from 'store/server'
    export const SetPopup;

    let 
        changeRbBtn = 10,
        changeCashBtn = Math.round(changeRbBtn * Math.round (10 * $serverDonateDoubleConvert));

	const onHandleInputTransfer = (value, isRb = false) => {
        value = Math.round(value.replace(/\D+/g, ""));
        if (value < 0) value = 0;
        else if (!isRb && value > Math.round(999999 * Math.round (10 * $serverDonateDoubleConvert))) value = Math.round(999999 * Math.round (10 * $serverDonateDoubleConvert));
        else if (isRb && value > 999999) value = 999999;

        if (!isRb) {
            changeCashBtn = value;
            changeRbBtn = Math.round(value / Math.round (10 * $serverDonateDoubleConvert));
            if (changeRbBtn < 0) changeRbBtn = 0;
        }
        else {            
            changeCashBtn = Math.round(value * Math.round (10 * $serverDonateDoubleConvert));
            changeRbBtn = value;
        }
    }

    const onChange = () => {
        if ($accountRedbucks < changeRbBtn)
            return window.notificationAdd(4, 9, `Недостаточно Redbucks!`, 3000);
        SetPopup ()
        executeClient ("client.donate.change", changeRbBtn);
    }
</script>

<div class="newdonate__change">
    <div class="newdonate__change-block" on:mouseenter on:mouseleave>
        <div class="newdonate__change-top">
            <div class="newdonate__change-element">
                <div class="newdonate__change-img redbucks"/>
                <input class="newdonate__change-input" bind:value={changeRbBtn} on:input={(event) => onHandleInputTransfer (event.target.value, true)} placeholder="10">
            </div>
            <div class="newdonate__change-element">
                <div class="newdonate__change-img progress"/>
                <div class="newdonate__change-curs">1 RB к ${Math.round (10 * $serverDonateDoubleConvert)}</div>
            </div>
            <div class="newdonate__change-element">
                <div class="newdonate__change-img money"/>
                <input class="newdonate__change-input" bind:value={changeCashBtn} on:input={(event) => onHandleInputTransfer (event.target.value)} placeholder="10">
            </div>
        </div>
        <div class="newdonate__change-bottom">
            <div class="newdonate__button_small" on:click={onChange}>
                <div class="newdonate__button-text">Обменять</div>
            </div>
        </div>
    </div>
    <div class="newdonate__escape">
        <div class="box-flex">
            <span class="donateicons-esc"/>
            <div class="newdonate__escape-title">ESC</div>
        </div>
        <div class="newdonate__escape-text">
            Нажми, чтобы закрыть
        </div>
    </div>
</div>

// cef_new/src/pages/donate/popup/popupchange.tsx
import React, { useState, useEffect } from 'react';
import { executeClient } from '#/shared/api/rage';
import { useSelector } from 'react-redux';
import { RootState } from '#/shared/store';
import "./popups.sass"

interface PopupChangeProps {
  SetPopup?: () => void;
}

const PopupChange: React.FC<PopupChangeProps> = ({ SetPopup }) => {
  // Access the store values
  const accountRedbucks = useSelector((state: RootState) => state.account.accountRedbucks);
  const serverDonateDoubleConvert = useSelector((state: RootState) => state.server.serverDonateDoubleConvert);
  
  // Initial state setup
  const [changeRbBtn, setChangeRbBtn] = useState<number>(10);
  const [changeCashBtn, setChangeCashBtn] = useState<number>(
    Math.round(10 * Math.round(10 * serverDonateDoubleConvert))
  );

  // Update cash value when conversion rate changes
  useEffect(() => {
    setChangeCashBtn(Math.round(changeRbBtn * Math.round(10 * serverDonateDoubleConvert)));
  }, [serverDonateDoubleConvert, changeRbBtn]);

  const onHandleInputTransfer = (value: string, isRb = false) => {
    let numValue = Math.round(Number(value.replace(/\D+/g, "")));
    
    if (numValue < 0) numValue = 0;
    else if (!isRb && numValue > Math.round(999999 * Math.round(10 * serverDonateDoubleConvert))) {
      numValue = Math.round(999999 * Math.round(10 * serverDonateDoubleConvert));
    }
    else if (isRb && numValue > 999999) numValue = 999999;

    if (!isRb) {
      setChangeCashBtn(numValue);
      const rbValue = Math.round(numValue / Math.round(10 * serverDonateDoubleConvert));
      setChangeRbBtn(rbValue < 0 ? 0 : rbValue);
    }
    else {
      setChangeRbBtn(numValue);
      setChangeCashBtn(Math.round(numValue * Math.round(10 * serverDonateDoubleConvert)));
    }
  };

  const onChange = () => {
    if (accountRedbucks < changeRbBtn) {
      return (window as any).notificationAdd(4, 9, `Недостаточно Redbucks!`, 3000);
    }
    // SetPopup();
    executeClient("client.donate.change", changeRbBtn);
  };

  return (
    <div className="newdonate__change">
      <div className="newdonate__change-block">
        <div className="newdonate__change-top">
          <div className="newdonate__change-element">
            <div className="newdonate__change-img redbucks" />
            <input 
              className="newdonate__change-input" 
              value={changeRbBtn} 
              onChange={(e) => onHandleInputTransfer(e.target.value, true)} 
              placeholder="10" 
            />
          </div>
          <div className="newdonate__change-element">
            <div className="newdonate__change-img progress" />
            <div className="newdonate__change-curs">
              1 RB к {Math.round(10 * serverDonateDoubleConvert)}
            </div>
          </div>
          <div className="newdonate__change-element">
            <div className="newdonate__change-img money" />
            <input 
              className="newdonate__change-input" 
              value={changeCashBtn} 
              onChange={(e) => onHandleInputTransfer(e.target.value)} 
              placeholder="10" 
            />
          </div>
        </div>
        <div className="newdonate__change-bottom">
          <div className="newdonate__button_small" onClick={onChange}>
            <div className="newdonate__button-text">Обменять</div>
          </div>
        </div>
      </div>
      <div className="newdonate__escape">
        <div className="box-flex">
          <span className="donateicons-esc" />
          <div className="newdonate__escape-title">ESC</div>
        </div>
        <div className="newdonate__escape-text">
          Нажми, чтобы закрыть
        </div>
      </div>
    </div>
  );
};

export default PopupChange;
