// src_cef/src/views/fractions/stock/index.svelte
<script>
    import { translateText } from 'lang'
    import { executeClient } from 'api/rage'
    import './assets/sass/stock.sass'
    export const viewData;

    let title = "",
        style = "",
        index = 0,
        count = [];

	
    $: {
        if (count !== JSON.parse(viewData)) {
            count = JSON.parse(viewData);
            onChange ();
        }
    }

    const leftHandle = () => {
        index--;
        if(index < 0) index = 4;
        onChange ();
    }

    const rightHandle = () => {
        index++;
        if(index > 4) index = 0;
        onChange ();
    }

    const onChange = () => {
        switch (index) {
            case 0:
                style = 'cash';
                title = translateText('fractions', 'Деньги');
                break;
            case 1:
                style = 'healkit';
                title = translateText('fractions', 'Аптечка');
                break;
            case 2:
                style = 'weed';
                title = translateText('fractions', 'Наркотики');
                break;
            case 3:
                style = 'weapons';
                title = translateText('fractions', 'Оружейные материалы');
                break;
            case 4:
                style = 'weaponsstock';
                title = translateText('fractions', 'Оружейный склад');
                break;
        } 
    }

    const takeHandle = () => {
        executeClient ('stockTake', index);
    }

    const putHandle = () => {
        executeClient ('stockPut', index);
    }

    const exitHandle = () => {
        executeClient ('stockExit');
    }
</script>

<div id="stock">
    <div class="stock module_stock">
        <div class="mod">
            <div class="arrows left icon-arrow" on:click={leftHandle} /> 
            <div class="contain">
                <div class="icon-block">
                    <div class={"ic " + style} />
                </div>
                <div class="title">{title}</div>
            </div>
            <div class="arrows icon-arrow" on:click={rightHandle} />
        </div>
        <div class="button">
            <div id="take" class="btn green" on:click={takeHandle}>{translateText('fractions', 'Взять')}</div>
            <div id="put" class="btn red" on:click={putHandle}>{translateText('fractions', 'Положить')}</div>
        </div>
        <div class="count">
            <div class="gray">{translateText('fractions', 'Всего')}:</div>
            <div class="white">{count[index]}</div>
        </div>
        <div class="button bottom">
            <div id="exit" class="exit btn red" on:click={exitHandle}>{translateText('fractions', 'Выход')}</div>
        </div>
    </div>
</div>

// cef_new/src/pages/fractions/stock/index.tsx
import React, { useState, useEffect } from 'react';
import { translateText } from '#/shared/locale';
import { executeClient } from '#/shared/api/rage';
import './assets/sass/stock.sass';

interface StockProps {
  viewData?: string;
}

const Stock: React.FC<StockProps> = ({ viewData }) => {
  const [title, setTitle] = useState<string>("");
  const [style, setStyle] = useState<string>("");
  const [index, setIndex] = useState<number>(0);
  const [count, setCount] = useState<number[]>([]);

  // Process viewData when it changes
  useEffect(() => {
    if (viewData) {
      const parsedData = JSON.parse(viewData);
      if (JSON.stringify(count) !== JSON.stringify(parsedData)) {
        setCount(parsedData);
      }
    }
  }, [viewData]);

  // Update style and title when index changes
  useEffect(() => {
    updateStyle();
  }, [index]);

  // Initialize component
  useEffect(() => {
    updateStyle();
  }, []);

  const leftHandle = () => {
    setIndex(prevIndex => {
      if (prevIndex <= 0) return 4;
      return prevIndex - 1;
    });
  };

  const rightHandle = () => {
    setIndex(prevIndex => {
      if (prevIndex >= 4) return 0;
      return prevIndex + 1;
    });
  };

  const updateStyle = () => {
    switch (index) {
      case 0:
        setStyle('cash');
        setTitle(translateText('fractions', 'Деньги'));
        break;
      case 1:
        setStyle('healkit');
        setTitle(translateText('fractions', 'Аптечка'));
        break;
      case 2:
        setStyle('weed');
        setTitle(translateText('fractions', 'Наркотики'));
        break;
      case 3:
        setStyle('weapons');
        setTitle(translateText('fractions', 'Оружейные материалы'));
        break;
      case 4:
        setStyle('weaponsstock');
        setTitle(translateText('fractions', 'Оружейный склад'));
        break;
    }
  };

  const takeHandle = () => {
    executeClient('stockTake', index);
  };

  const putHandle = () => {
    executeClient('stockPut', index);
  };

  const exitHandle = () => {
    executeClient('stockExit');
  };

  return (
    <div id="stock">
      <div className="stock module_stock">
        <div className="mod">
          <div className="arrows left icon-arrow" onClick={leftHandle} /> 
          <div className="contain">
            <div className="icon-block">
              <div className={`ic ${style}`} />
            </div>
            <div className="title">{title}</div>
          </div>
          <div className="arrows icon-arrow" onClick={rightHandle} />
        </div>
        <div className="button">
          <div id="take" className="btn green" onClick={takeHandle}>
            {translateText('fractions', 'Взять')}
          </div>
          <div id="put" className="btn red" onClick={putHandle}>
            {translateText('fractions', 'Положить')}
          </div>
        </div>
        <div className="count">
          <div className="gray">{translateText('fractions', 'Всего')}:</div>
          <div className="white">{count[index] || 0}</div>
        </div>
        <div className="button bottom">
          <div id="exit" className="exit btn red" onClick={exitHandle}>
            {translateText('fractions', 'Выход')}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Stock;
