// src_cef/src/views/house/menu/elements/parking.svelte
<script>
    import { vehicleModelsToMoto, colorData } from '@/json/vehicles'


    import {executeClient, executeClientAsync, executeClientAsyncToGroup} from 'api/rage'
	import { selectPopup, popudData } from '@/views/house/menu/stores.js';

    let houseData = {}
    executeClientAsync("phone.house.houseData").then((result) => {
        if (hasJsonStructure(result))
            houseData = JSON.parse(result);

        updateMaxParkingPlaces ()
    });

    let garagesData = [];
    executeClientAsync("phone.house.garagesData").then((result) => {
        if (hasJsonStructure(result))
            garagesData = JSON.parse(result);

        updateMaxParkingPlaces ()
    });


    let maxParkingPlaces = 2;

    const updateMaxParkingPlaces = () => {
        if (houseData && houseData.garageType != undefined && garagesData && garagesData [houseData.garageType])
            maxParkingPlaces = garagesData [houseData.garageType].MaxCars;
    }





    let houseCars = {};
    let selectCar = {};
    let carsData = [];

    const updateLoad = () => {
        executeClientAsync("phone.cars.getCarsList").then((result) => {
            if (hasJsonStructure(result)) {
                carsData = JSON.parse(result);
                //
                if (selectCar && selectCar.place !== undefined) {

                    const placeId = selectCar.place;
                    const carIndex = carsData.findIndex(car => car.number == selectCar.number);
                    if (carIndex != -1 && carsData [carIndex]) {
                        selectCar = carsData [carIndex];
                        selectCar.place = placeId;
                    } else {
                        selectCar = {};
                        selectCar.place = placeId;
                    }
                }
                //

                let newCarsData = {};

                carsData.forEach(car => {
                    if (car && typeof car.place === "number" && car.place >= 0) {
                        newCarsData [car.place] = car;
                    }
                });

                houseCars = newCarsData;

                isUpdate = false;
                selectCar = {};
            }
        });
    }

    updateLoad ();
    import { addListernEvent } from 'api/functions';
    addListernEvent("phoneCarsLoad", updateLoad);


    let selectPage = 0;

    const onLeft = () => {
        if (--selectPage < 0)
            selectPage = 0;
    }

    const onRight = () => {
        const count = Math.ceil (maxParkingPlaces / 10);
        
        if (++selectPage >= count - 1)
            selectPage = count - 1;
    }


    const handleKeyUp = (event) => {
        
        const { keyCode } = event;

        switch(keyCode) {
            case 37:
                onLeft ();
                break;
            case 39:
                onRight ();
                break;
            case 27: // esc                    
                onExit ();
                break;
            case 13:
                onOpen ()
                break;
        }
    }

    const onSelectCar = (index) => {
        if (houseCars [index]) {
            selectCar = houseCars [index];
            selectCar.place = index;
        } else {                
            selectCar = {};
            selectCar.place = index;
        }
    }
    
    let isUpdate = false;

    const OnChangeCars = (sqlId) => {
        if (!window.loaderData.delay ("OnChangeCars", 1))
            return;
        if (isUpdate)
            return;
            
        isUpdate = true;
        executeClient ("client.garage.parking", sqlId, selectCar.place);
    
        selectCar = {};
    }

    import {hasJsonStructure} from "api/functions";


    const getColor = (color) => {
        if (typeof color == "number" || colorData[color] !== undefined) {
            return colorData[color];
        }
        return `rgba(${color.Red},${color.Green},${color.Blue},1)`;
    }

    const onOpen = () => {
        if (houseData && houseData.garageType != undefined && garagesData && garagesData [houseData.garageType + 1])
            selectPopup.set ("popupUpdateGarage")
    }

    export const onExit;
</script>
    
<svelte:window on:keyup={handleKeyUp} />

<div class="house__parking_box">
    <div class="house__mainmenu_block parking">
        {#if selectCar && selectCar.place !== undefined}
            {#each carsData as car, index}
                {#if car.number !== selectCar.number && !car.isAir}
                    <div class="house__mainmenu_categorie" on:click={() => OnChangeCars (car.sqlId)}>
                        <div class="line" style="background: {getColor (car.color)};"></div>
                        {car.model.toUpperCase()} [{car.number}] {car.sell ? " (Личная)" : ""}
                    </div>
                {/if}
            {/each}
        {/if}
    </div>
    <div class="house__parking">
        <div class="house__header">Управление парковкой</div>
        <div class="house__floor">
            <div class="house__floor_lines">
                {#each Array(Math.ceil (maxParkingPlaces / 10)).fill(0) as _, index}
                <div class="house__floor_line" class:active={selectPage === index} on:click={() => selectPage = index} />
                {/each}
            </div>
            <div class="box-flex">
                <div class="house__button_white" on:click={onLeft}>&#8592;</div>
                <div class="box-column">
                    <div class="house__current_floor">{selectPage + 1}</div>
                    <div class="house__gray">Текущий этаж</div>
                </div>
                <div class="house__button_white" on:click={onRight}>&#8594;</div>
            </div>
        </div>
        <div class="house__parking_names">
            {#each Array(5).fill(0) as _, index}
                {#if index + (10 * selectPage) < maxParkingPlaces}
                    {#if houseCars [index + (10 * selectPage)] != undefined}
                    <div class="house__car_name">{houseCars [index + (10 * selectPage)].model} [{houseCars [index + (10 * selectPage)].number}]</div>
                    {:else}                 
                    <div class="house__car_name">Свободно</div>
                    {/if}
                {/if}
            {/each}
        </div>
        <div class="house__parking_top">
            <div class="house__parking_places">
                {#each Array(5).fill(0) as _, index}
                    {#if index + (10 * selectPage) < maxParkingPlaces}
                        <div class="house__car_place top" on:click={() => onSelectCar (index + (10 * selectPage))}>
                            <div class="house__car_position">{index + (10 * selectPage) + 1}</div>
                            {#if houseCars [index + (10 * selectPage)] != undefined}
                                {#if vehicleModelsToMoto.includes (houseCars [index + (10 * selectPage)].model.toLowerCase())}
                                <div class="houseicon-bike-top house__car_image" style="color: {getColor (houseCars [index + (10 * selectPage)].color)}">
                                    <div class="house__bike_details"></div>
                                </div>
                                {:else}
                                <div class="houseicon-car-top house__car_image" style="color: {getColor (houseCars [index + (10 * selectPage)].color)}">
                                    <div class="house__car_details"></div>
                                </div>
                                {/if}
                            {:else}
                            <div class="house__circle_green">+</div>
                            {/if}
                        </div>
                    {/if}
                {/each}
            </div>
        </div>
        <div class="box-column box-center m-60">
            <div class="house__text_big">{maxParkingPlaces}</div>
            <div class="house__gray">Всего доступно мест</div>
        </div>
        <div class="house__parking_top bottom">
            <div class="house__parking_places bottom">
                {#each Array(5).fill(0) as _, index}
                    {#if index + (5) + (10 * selectPage) < maxParkingPlaces}
                        <div class="house__car_place top" on:click={() => onSelectCar (index + (5) + (10 * selectPage))}>
                            <div class="house__car_position">{index + (5) + (10 * selectPage) + 1}</div>
                            {#if houseCars [index + (5) + (10 * selectPage)] != undefined}

                            {#if vehicleModelsToMoto.includes (houseCars [index + (5) + (10 * selectPage)].model.toLowerCase())}                            
                            <div class="houseicon-bike-top house__car_image" style="color: {getColor (houseCars [index + (5) + (10 * selectPage)].color)}">
                                <div class="house__bike_details"></div>
                            </div>
                            {:else}
                            <div class="houseicon-car-top house__car_image" style="color: {getColor (houseCars [index + (5) + (10 * selectPage)].color)}">
                                <div class="house__car_details"></div>
                            </div>
                            {/if}
                            {:else}
                            <div class="house__circle_green">+</div>
                            {/if}
                        </div>
                    {/if}
                {/each}
            </div>
        </div>
        <div class="house__parking_names bottom">
            {#each Array(5).fill(0) as _, index}
                {#if index + (5) + (10 * selectPage) < maxParkingPlaces}
                    {#if houseCars [index + (5) + (10 * selectPage)] != undefined}
                    <div class="house__car_name">{houseCars [index + (5) + (10 * selectPage)].model} [{houseCars [index + (5) + (10 * selectPage)].number}]</div>
                    {:else}                
                    <div class="house__car_name">Свободно</div>
                    {/if}
                {/if}
            {/each}
        </div>
        <div class="houseicon-house house__background"></div>
    </div>
    <div class="house__mainmenu_block parking">
    
    </div>
</div>
<div class="box-between">
    {#if houseData && houseData.garageType != undefined && garagesData && garagesData [houseData.garageType + 1]}
    <div class="house_bottom_buttons back" on:click={onOpen}>
        <div>Улучшить гараж</div>
        <div class="house_bottom_button">ENTER</div>
    </div>
    {/if}
    <div class="house_bottom_buttons esc" on:click={onExit}>
        <div>Выйти</div>
        <div class="house_bottom_button">ESC</div>
    </div>
</div>

// cef_new/src/pages/house/menu/elements/parking.tsx
import React, { useState, useEffect } from 'react';

import { executeClient, executeClientAsync } from '#/shared/api/rage';
import { hasJsonStructure } from '#/shared/api/functions';
import { ENVIRONMENT } from '#/env';

// Mock data for development
const MOCK_VEHICLE_MODELS_TO_MOTO = ['faggio', 'pcj', 'bati', 'akuma', 'hakuchou', 'double', 'bf400'];

const MOCK_COLOR_DATA: Record<string | number, string> = {
  0: 'rgba(0, 0, 0, 1)',
  1: 'rgba(255, 255, 255, 1)',
  2: 'rgba(255, 0, 0, 1)',
  3: 'rgba(0, 255, 0, 1)',
  4: 'rgba(0, 0, 255, 1)',
  5: 'rgba(255, 255, 0, 1)',
  6: 'rgba(255, 0, 255, 1)',
  7: 'rgba(0, 255, 255, 1)',
};

const MOCK_HOUSE_DATA = {
  garageType: 1,
  address: "Alta Street, Apartment 57",
  owner: "John_Doe",
  locked: false,
  price: 500000
};

const MOCK_GARAGES_DATA = [
  { MaxCars: 2, Price: 50000, Name: "Малый гараж" },
  { MaxCars: 6, Price: 150000, Name: "Средний гараж" },
  { MaxCars: 10, Price: 300000, Name: "Большой гараж" },
  { MaxCars: 20, Price: 600000, Name: "Премиум гараж" }
];

const MOCK_CARS_DATA = [
  { 
    sqlId: 1001, 
    model: "Zentorno", 
    number: "ABC123", 
    sell: true, 
    color: 2, 
    place: 0,
    isAir: false
  },
  { 
    sqlId: 1002, 
    model: "Elegy", 
    number: "XYZ789", 
    sell: true, 
    color: {Red: 255, Green: 100, Blue: 100}, 
    place: 2,
    isAir: false
  },
  { 
    sqlId: 1003, 
    model: "faggio", 
    number: "MOT001", 
    sell: false, 
    color: 6, 
    place: 4,
    isAir: false
  },
  { 
    sqlId: 1004, 
    model: "T20", 
    number: "SPD001", 
    sell: true, 
    color: {Red: 50, Green: 50, Blue: 200}, 
    isAir: false
  },
  { 
    sqlId: 1005, 
    model: "bati", 
    number: "MOT002", 
    sell: true, 
    color: 5, 
    isAir: false
  }
];

interface Car {
  sqlId: number;
  model: string;
  number: string;
  sell: boolean;
  color: number | { Red: number; Green: number; Blue: number };
  place?: number;
  isAir?: boolean;
}

interface ParkingProps {
  onExit?: () => void;
}

const ParkingComponent: React.FC<ParkingProps> = ({ onExit = () => console.log('Exit parking') }) => {
  const [houseData, setHouseData] = useState<any>(null);
  const [garagesData, setGaragesData] = useState<any[]>([]);
  const [maxParkingPlaces, setMaxParkingPlaces] = useState<number>(2);
  const [houseCars, setHouseCars] = useState<Record<number, Car>>({});
  const [selectCar, setSelectCar] = useState<Partial<Car & { place?: number }>>({});
  const [carsData, setCarsData] = useState<Car[]>([]);
  const [selectPage, setSelectPage] = useState<number>(0);
  const [isUpdate, setIsUpdate] = useState<boolean>(false);

  // For development mode, initialize with mock data
  useEffect(() => {
    if (ENVIRONMENT === 'development') {
      setHouseData(MOCK_HOUSE_DATA);
      setGaragesData(MOCK_GARAGES_DATA);
      setCarsData(MOCK_CARS_DATA);
      
      // Setup mock global objects
      if (!window.loaderData) {
        window.loaderData = {
          delay: (key: string, seconds: number) => true
        };
      }
    } else {
      // In production, fetch real data
      fetchHouseData();
      fetchGaragesData();
      updateLoad();
    }
  }, []);

  // Update maxParkingPlaces when houseData or garagesData changes
  useEffect(() => {
    updateMaxParkingPlaces();
  }, [houseData, garagesData]);

  // Process cars data whenever it changes
  useEffect(() => {
    processCarsData();
  }, [carsData]);

  const fetchHouseData = async () => {
    try {
      const result = await executeClientAsync("phone.house.houseData");
      if (hasJsonStructure(result)) {
        const parsedData = JSON.parse(result);
        setHouseData(parsedData);
      }
    } catch (error) {
      console.error('Error fetching house data:', error);
    }
  };

  const fetchGaragesData = async () => {
    try {
      const result = await executeClientAsync("phone.house.garagesData");
      if (hasJsonStructure(result)) {
        const parsedData = JSON.parse(result);
        setGaragesData(parsedData);
      }
    } catch (error) {
      console.error('Error fetching garages data:', error);
    }
  };

  const updateMaxParkingPlaces = () => {
    if (houseData && houseData.garageType !== undefined && 
        garagesData && garagesData[houseData.garageType]) {
      setMaxParkingPlaces(garagesData[houseData.garageType].MaxCars);
    }
  };

  const updateLoad = async () => {
    try {
      const result = await executeClientAsync("phone.cars.getCarsList");
      if (hasJsonStructure(result)) {
        const parsedData = JSON.parse(result);
        setCarsData(parsedData);
      }
    } catch (error) {
      console.error('Error loading cars data:', error);
      // For development, use mock data
      if (ENVIRONMENT === 'development') {
        setCarsData(MOCK_CARS_DATA);
      }
    }
  };

  const processCarsData = () => {
    if (carsData.length > 0) {
      // Handle selected car
      if (selectCar && selectCar.place !== undefined) {
        const placeId = selectCar.place;
        const carIndex = carsData.findIndex(car => car.number === selectCar.number);
        if (carIndex !== -1 && carsData[carIndex]) {
          setSelectCar({
            ...carsData[carIndex],
            place: placeId
          });
        } else {
          setSelectCar({ place: placeId });
        }
      }

      // Process houseCars
      const newCarsData: Record<number, Car> = {};
      carsData.forEach(car => {
        if (car && typeof car.place === "number" && car.place >= 0) {
          newCarsData[car.place] = car;
        }
      });
      
      setHouseCars(newCarsData);
      setIsUpdate(false);
      setSelectCar({});
    }
  };

  const onLeft = () => {
    setSelectPage(prev => Math.max(0, prev - 1));
  };

  const onRight = () => {
    const count = Math.ceil(maxParkingPlaces / 10);
    setSelectPage(prev => Math.min(count - 1, prev + 1));
  };

  const handleKeyUp = (event: React.KeyboardEvent<HTMLDivElement> | KeyboardEvent) => {
    const { keyCode } = event;
    
    switch (keyCode) {
      case 37: // left arrow
        onLeft();
        break;
      case 39: // right arrow
        onRight();
        break;
      case 27: // esc
        onExit();
        break;
      case 13: // enter
        onOpen();
        break;
    }
  };

  const onSelectCar = (index: number) => {
    if (houseCars[index]) {
      setSelectCar({
        ...houseCars[index],
        place: index
      });
    } else {
      setSelectCar({ place: index });
    }
  };

  const onChangeCars = (sqlId: number) => {
    if (!window.loaderData.delay("OnChangeCars", 1)) {
      return;
    }
    
    if (isUpdate) {
      return;
    }
    
    setIsUpdate(true);
    executeClient("client.garage.parking", sqlId, selectCar.place);
    setSelectCar({});
    
    // In development, simulate the update
    if (ENVIRONMENT === 'development') {
      setTimeout(() => {
        const updatedCarsData = [...carsData];
        const carIndex = updatedCarsData.findIndex(car => car.sqlId === sqlId);
        
        if (carIndex !== -1 && selectCar.place !== undefined) {
          updatedCarsData[carIndex] = {
            ...updatedCarsData[carIndex],
            place: selectCar.place
          };
          setCarsData(updatedCarsData);
        }
        
        setIsUpdate(false);
      }, 500);
    }
  };

  const getColor = (color: number | { Red: number; Green: number; Blue: number }) => {
    if (typeof color === "number" || MOCK_COLOR_DATA[color] !== undefined) {
      return MOCK_COLOR_DATA[color];
    }
    return `rgba(${color.Red},${color.Green},${color.Blue},1)`;
  };

  const onOpen = () => {
    if (houseData && 
        houseData.garageType !== undefined && 
        garagesData && 
        garagesData[houseData.garageType + 1]) {
      console.log("Opening garage upgrade popup");
      // In a real app, this would open the upgrade popup
      // selectPopup.set("popupUpdateGarage");
    }
  };

  // Attach keyup event listener to window
  useEffect(() => {
    const handleKeyUpGlobal = (event: KeyboardEvent) => {
      handleKeyUp(event);
    };
    
    window.addEventListener('keyup', handleKeyUpGlobal);
    
    return () => {
      window.removeEventListener('keyup', handleKeyUpGlobal);
    };
  }, [selectCar, isUpdate]); // Re-add when these dependencies change

  return (
    <>
      <div className="house__parking_box">
        <div className="house__mainmenu_block parking">
          {selectCar && selectCar.place !== undefined && (
            carsData.map((car, index) => (
              car.number !== selectCar.number && !car.isAir && (
                <div 
                  key={index}
                  className="house__mainmenu_categorie" 
                  onClick={() => onChangeCars(car.sqlId)}
                >
                  <div 
                    className="line" 
                    style={{ background: getColor(car.color) }}
                  ></div>
                  {car.model.toUpperCase()} [{car.number}] {car.sell ? " (Личная)" : ""}
                </div>
              )
            ))
          )}
        </div>
        <div className="house__parking">
          <div className="house__header">Управление парковкой</div>
          <div className="house__floor">
            <div className="house__floor_lines">
              {Array(Math.ceil(maxParkingPlaces / 10)).fill(0).map((_, index) => (
                <div 
                  key={index}
                  className={`house__floor_line ${selectPage === index ? 'active' : ''}`}
                  onClick={() => setSelectPage(index)}
                />
              ))}
            </div>
            <div className="box-flex">
              <div className="house__button_white" onClick={onLeft}>&#8592;</div>
              <div className="box-column">
                <div className="house__current_floor">{selectPage + 1}</div>
                <div className="house__gray">Текущий этаж</div>
              </div>
              <div className="house__button_white" onClick={onRight}>&#8594;</div>
            </div>
          </div>
          <div className="house__parking_names">
            {Array(5).fill(0).map((_, index) => (
              index + (10 * selectPage) < maxParkingPlaces && (
                <div key={index} className="house__car_name">
                  {houseCars[index + (10 * selectPage)] ? 
                    `${houseCars[index + (10 * selectPage)].model} [${houseCars[index + (10 * selectPage)].number}]` : 
                    'Свободно'}
                </div>
              )
            ))}
          </div>
          <div className="house__parking_top">
            <div className="house__parking_places">
              {Array(5).fill(0).map((_, index) => (
                index + (10 * selectPage) < maxParkingPlaces && (
                  <div 
                    key={index} 
                    className="house__car_place top" 
                    onClick={() => onSelectCar(index + (10 * selectPage))}
                  >
                    <div className="house__car_position">{index + (10 * selectPage) + 1}</div>
                    {houseCars[index + (10 * selectPage)] ? (
                      MOCK_VEHICLE_MODELS_TO_MOTO.includes(houseCars[index + (10 * selectPage)].model.toLowerCase()) ? (
                        <div 
                          className="houseicon-bike-top house__car_image"
                          style={{ color: getColor(houseCars[index + (10 * selectPage)].color) }}
                        >
                          <div className="house__bike_details"></div>
                        </div>
                      ) : (
                        <div 
                          className="houseicon-car-top house__car_image"
                          style={{ color: getColor(houseCars[index + (10 * selectPage)].color) }}
                        >
                          <div className="house__car_details"></div>
                        </div>
                      )
                    ) : (
                      <div className="house__circle_green">+</div>
                    )}
                  </div>
                )
              ))}
            </div>
          </div>
          <div className="box-column box-center m-60">
            <div className="house__text_big">{maxParkingPlaces}</div>
            <div className="house__gray">Всего доступно мест</div>
          </div>
          <div className="house__parking_top bottom">
            <div className="house__parking_places bottom">
              {Array(5).fill(0).map((_, index) => (
                index + (5) + (10 * selectPage) < maxParkingPlaces && (
                  <div 
                    key={index} 
                    className="house__car_place top" 
                    onClick={() => onSelectCar(index + (5) + (10 * selectPage))}
                  >
                    <div className="house__car_position">{index + (5) + (10 * selectPage) + 1}</div>
                    {houseCars[index + (5) + (10 * selectPage)] ? (
                      MOCK_VEHICLE_MODELS_TO_MOTO.includes(houseCars[index + (5) + (10 * selectPage)].model.toLowerCase()) ? (
                        <div 
                          className="houseicon-bike-top house__car_image"
                          style={{ color: getColor(houseCars[index + (5) + (10 * selectPage)].color) }}
                        >
                          <div className="house__bike_details"></div>
                        </div>
                      ) : (
                        <div 
                          className="houseicon-car-top house__car_image"
                          style={{ color: getColor(houseCars[index + (5) + (10 * selectPage)].color) }}
                        >
                          <div className="house__car_details"></div>
                        </div>
                      )
                    ) : (
                      <div className="house__circle_green">+</div>
                    )}
                  </div>
                )
              ))}
            </div>
          </div>
          <div className="house__parking_names bottom">
            {Array(5).fill(0).map((_, index) => (
              index + (5) + (10 * selectPage) < maxParkingPlaces && (
                <div key={index} className="house__car_name">
                  {houseCars[index + (5) + (10 * selectPage)] ? 
                    `${houseCars[index + (5) + (10 * selectPage)].model} [${houseCars[index + (5) + (10 * selectPage)].number}]` : 
                    'Свободно'}
                </div>
              )
            ))}
          </div>
          <div className="houseicon-house house__background"></div>
        </div>
        <div className="house__mainmenu_block parking">
          {/* Right side content if needed */}
        </div>
      </div>
      <div className="box-between">
        {houseData && 
         houseData.garageType !== undefined && 
         garagesData && 
         garagesData[houseData.garageType + 1] && (
          <div className="house_bottom_buttons back" onClick={onOpen}>
            <div>Улучшить гараж</div>
            <div className="house_bottom_button">ENTER</div>
          </div>
        )}
        <div className="house_bottom_buttons esc" onClick={onExit}>
          <div>Выйти</div>
          <div className="house_bottom_button">ESC</div>
        </div>
      </div>
    </>
  );
};

// Add window type declaration
declare global {
  interface Window {
    loaderData: {
      delay: (key: string, seconds: number) => boolean;
    };
  }
}

export default ParkingComponent;
